### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by jmolmo** [red-hat-storage/cockpit-ceph-installer#12]
I showed to Luis Rico (lricomor@redhat.com) the interface of the plugin, and he has commented me that the acronyms we are used to use for the Ceph daemons (mon, osd, rgw...) are not known for people with no experience with Ceph.

Being this kind of people part of  our main "destination" target, it seems sensible to make easy to understand this acronyms , and even to use the plugin itself as an educational tool to learn the Ceph vocabulary.

My proposal is to add in the first page of the installer a "textual" section where this acronyms appear together with a brief explanation of the term.
Doing that, it seems more natural to use the acronyms in the next pages of the installation wizard.

Ex:

OSD: Object storage daemon. A daemon running in a server and associated with one or more physical disks of this server. Data is stored using this daemons.

MON:  Is the cluster monitor daemon for the Ceph distributed file system. HA and resiliency forces to have several different MONS running in different servers.
...

**Comment by pcuzner** [comment]
Agree. Instead of introducing a new page, we could explore a ? icon with a tooltip or a popover. The tooltip component is already done and used for an (i) icon. Thoughts?

**Comment by jmolmo** [comment]
A tooltip is better idea!

**Comment by pcuzner** [comment]
I'll implement this with a (i) icon against Roles in the Add Hosts modal, and see what that looks like

**Comment by pcuzner** [comment]
heres a screen shot showing the tooltip option and what that would look like on hover over the (i) symbol. You can also see the notifcation area - that is currently used for errors. Instead of a tooltip, we could use the notification area to show a description of the role, when the user clicks on a (?) symbol for example.
![Screenshot_20191016_180104](https://user-images.githubusercontent.com/3703087/66889614-9b435d80-f03f-11e9-8327-fd2a6d07aacf.png)

@alfonsomthd @jmolmo  thoughts?

**Comment by alfonsomthd** [comment]
@pcuzner The tooltip seems OK. What about putting a link to the documentation in addition to the brief description of the component?

**Comment by pcuzner** [comment]
0.9-3 has a changed add hosts dialog (roles are now arranged veritically), that includes tool tips for all the roles the installer supports
